services:
  spelling-bee-web:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: spelling-bee-duel-web
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
