services:
  spelling-bee-web:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: spelling-bee-web
    restart: unless-stopped
    ports:
      - "3005:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    volumes:
      - /opt/data/spelling-bee-puzzles/data:/app/data:ro
